# Generated by Django 4.2.5 on 2023-10-10 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DriveWatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
