# Generated by Django 4.2.5 on 2023-10-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveWatch', '0003_ride_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='ride',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
