version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    networks:
      - backend

  web:
    build: .
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT_HTTP:-80}:80"
      - "${NGINX_PORT_HTTPS:-443}:443"
    volumes:
      - ${NGINX_CONF:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf:ro
      - ${SSL_CERTS_PATH:-./certs}:/etc/nginx/ssl:ro
      - static_volume:/app/staticfiles
    depends_on:
      - web
    env_file:
      - .env
    networks:
      - backend

volumes:
  db_data:
  static_volume:

networks:
  backend:
