version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    networks:
      - backend

  web:
    build: .
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - static_volume:/app/staticfiles
    depends_on:
      - web
    networks:
      - backend

  certbot_init:
    image: certbot/certbot
    depends_on:
      - nginx
    env_file:
      - .env
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: certbot
    command: >
      certonly --webroot
      --webroot-path=/var/www/certbot
      --email ${CERTBOT_EMAIL}
      --agree-tos
      --no-eff-email
      -d leon-schoenberg.de
      -d www.leon-schoenberg.de
    networks:
      - backend

  certbot_renew:
    image: certbot/certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done"
    networks:
      - backend

volumes:
  db_data:
  certbot_certs:
  certbot_www:
  static_volume:

networks:
  backend:
