version: '3.9'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf.certbot:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/letsencrypt
      - ./certbot-www:/var/www/certbot
    networks:
      - backend

  certbot_init:
    image: certbot/certbot
    depends_on:
      - nginx
    env_file:
      - .env
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-www:/var/www/certbot
    entrypoint: certbot
    command: >
      certonly --webroot
      --webroot-path=/var/www/certbot
      --email ${CERTBOT_EMAIL}
      --agree-tos
      --no-eff-email
      -d ${NGINX_DOMAIN}
      -d ${NGINX_WWW_DOMAIN}
    networks:
      - backend

networks:
  backend:
