version: '3.8'

services:
  home_server:
    image: leonxs/home_server:latest
    env_file: .env
    depends_on:
      - db
    expose:
      - "8000"  # Intern für nginx erreichbar
    volumes:
      - static_volume:/app/static/

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - home_server
    volumes:
      - static_volume:/static/:ro  # statische Dateien nur lesbar
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
  static_volume:
