# Generated by Django 4.2.5 on 2023-09-26 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date_of_creation', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('kcal', models.IntegerField()),
                ('fat', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('sugar', models.FloatField()),
                ('proteins', models.FloatField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserDishAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('eaten', models.DateTimeField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeightWatch.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-eaten'],
            },
        ),
        migrations.CreateModel(
            name='DishFoodAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeightWatch.dish')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeightWatch.food')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='foods',
            field=models.ManyToManyField(through='WeightWatch.DishFoodAmount', to='WeightWatch.food'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('color', models.CharField(default='#ffff90', max_length=8)),
                ('food', models.ManyToManyField(to='WeightWatch.food')),
            ],
        ),
    ]
