# Generated by Django 4.2.5 on 2024-01-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeightWatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdishamount',
            options={'ordering': ['eaten']},
        ),
    ]
