# Generated by Django 4.2.5 on 2024-01-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeightWatch', '0002_alter_userdishamount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdishamount',
            options={},
        ),
    ]
